# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Destination.create(name: "Seville, Spain", airport_code: "SVQ", url: "https://www.lonelyplanet.com/spain/seville")
Destination.create(name: "Antwerp, Belgium", airport_code: "ANR", url: "https://www.lonelyplanet.com/belgium/flanders/antwerp")
Destination.create(name: "Canberra, Australia", airport_code: "CBR", url: "https://www.lonelyplanet.com/australia/australian-capital-territory/canberra")
Destination.create(name: "Kaohsiung, Taiwan", airport_code: "KHH", url: "https://www.lonelyplanet.com/taiwan/southern-taiwan/kaohsiung-city")
Destination.create(name: "Hamburg, Germany", airport_code: "HAM", url: "https://www.lonelyplanet.com/germany/hamburg")
Destination.create(name: "San Juan, Puerto Rico", airport_code: "SJU", url: "https://www.lonelyplanet.com/puerto-rico/san-juan")
Destination.create(name: "Rome, Italy", airport_code: "FCO", url: "https://www.lonelyplanet.com/italy/rome")
Destination.create(name: "Guanajuato, Mexico", airport_code: "BJX", url: "https://www.lonelyplanet.com/mexico/northern-central-highlands/guanajuato")
Destination.create(name: "Oslo, Norway", airport_code: "OSL", url: "https://www.lonelyplanet.com/norway/oslo")
Destination.create(name: "Essaouira, Morocco", airport_code: "ESU", url: "https://www.lonelyplanet.com/morocco/the-atlantic-coast/essaouira")
Destination.create(name: "Hunan, China", airport_code: "CSX", url: "https://www.lonelyplanet.com/china/hunan")
Destination.create(name: "Tallin, Estonia", airport_code: "TLL", url: "https://www.lonelyplanet.com/estonia/tallinn")
Destination.create(name: "Toronto, Canada", airport_code: "YYZ", url: "https://www.lonelyplanet.com/canada/toronto")
Destination.create(name: "Solta, Croatia", airport_code: "ZAG", url: "https://www.lonelyplanet.com/croatia/solta-island")
Destination.create(name: "Iguazu Falls, Argentina", airport_code: "IGU", url: "https://www.lonelyplanet.com/argentina/iguazu-falls")
Destination.create(name: "Tokyo, Japan", airport_code: "HND", url: "https://www.lonelyplanet.com/japan/tokyo")
Destination.create(name: "London, England", airport_code: "LHR", url: "https://www.lonelyplanet.com/england/london")
Destination.create(name: "Cape Town, South Africa", airport_code: "CPT", url: "https://www.lonelyplanet.com/south-africa/cape-town")
Destination.create(name: "Gangneung, Korea", airport_code: "ICN", url: "https://www.lonelyplanet.com/south-korea/gang-won-do/gangneung")
Destination.create(name: "Paris, France", airport_code: "CDG", url: "https://www.lonelyplanet.com/france/paris")

User.create(email: "mary@email.com", password: "test123")
User.create(email: "tommy@email.com", password: "test123")
User.create(email: "june@email.com", password: "test123")

DestinationRating.create(user_id: 1, destination_id: 1, rating: 3)
DestinationRating.create(user_id: 1, destination_id: 2, rating: 3)
DestinationRating.create(user_id: 1, destination_id: 3, rating: 3)
DestinationRating.create(user_id: 1, destination_id: 4, rating: 3)
DestinationRating.create(user_id: 1, destination_id: 5, rating: 3)
DestinationRating.create(user_id: 1, destination_id: 6, rating: 3)
DestinationRating.create(user_id: 1, destination_id: 7, rating: 3)
DestinationRating.create(user_id: 1, destination_id: 8, rating: 4)
DestinationRating.create(user_id: 1, destination_id: 9, rating: 4)
DestinationRating.create(user_id: 1, destination_id: 10, rating: 4)
DestinationRating.create(user_id: 1, destination_id: 11, rating: 4)
DestinationRating.create(user_id: 1, destination_id: 12, rating: 4)
DestinationRating.create(user_id: 1, destination_id: 13, rating: 1)
DestinationRating.create(user_id: 1, destination_id: 14, rating: 3)
DestinationRating.create(user_id: 1, destination_id: 15, rating: 2)
DestinationRating.create(user_id: 1, destination_id: 16, rating: 2)
DestinationRating.create(user_id: 1, destination_id: 17, rating: 4)
DestinationRating.create(user_id: 1, destination_id: 18, rating: 5)
DestinationRating.create(user_id: 1, destination_id: 19, rating: 5)
DestinationRating.create(user_id: 1, destination_id: 20, rating: 5)

DestinationRating.create(user_id: 2, destination_id: 1, rating: 1)
DestinationRating.create(user_id: 2, destination_id: 2, rating: 1)
DestinationRating.create(user_id: 2, destination_id: 3, rating: 1)
DestinationRating.create(user_id: 2, destination_id: 4, rating: 4)
DestinationRating.create(user_id: 2, destination_id: 5, rating: 1)
DestinationRating.create(user_id: 2, destination_id: 6, rating: 5)
DestinationRating.create(user_id: 2, destination_id: 7, rating: 1)
DestinationRating.create(user_id: 2, destination_id: 8, rating: 5)
DestinationRating.create(user_id: 2, destination_id: 9, rating: 1)
DestinationRating.create(user_id: 2, destination_id: 10, rating: 3)
DestinationRating.create(user_id: 2, destination_id: 11, rating: 5)
DestinationRating.create(user_id: 2, destination_id: 12, rating: 3)
DestinationRating.create(user_id: 2, destination_id: 13, rating: 1)
DestinationRating.create(user_id: 2, destination_id: 14, rating: 2)
DestinationRating.create(user_id: 2, destination_id: 15, rating: 3)
DestinationRating.create(user_id: 2, destination_id: 16, rating: 4)
DestinationRating.create(user_id: 2, destination_id: 17, rating: 1)
DestinationRating.create(user_id: 2, destination_id: 18, rating: 4)
DestinationRating.create(user_id: 2, destination_id: 19, rating: 5)
DestinationRating.create(user_id: 2, destination_id: 20, rating: 1)

DestinationRating.create(user_id: 3, destination_id: 1, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 2, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 3, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 4, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 5, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 6, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 7, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 8, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 9, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 10, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 11, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 12, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 13, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 14, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 15, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 16, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 17, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 18, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 19, rating: 5)
DestinationRating.create(user_id: 3, destination_id: 20, rating: 5)

DestinationCostIndex.create(destination_id: 1, currency: "EUR", start_exchange_rate: 0.85, avg_mcmeal: 8.06, avg_airfare: 565.41, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 2, currency: "EUR", start_exchange_rate: 0.85, avg_mcmeal: 10.23, avg_airfare: 1994.56, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 3, currency: "AUD", start_exchange_rate: 1.31, avg_mcmeal: 7.17, avg_airfare: 1652.41, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 4, currency: "TWD", start_exchange_rate: 29.80, avg_mcmeal: 4.03, avg_airfare: 3374.13, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 5, currency: "EUR", start_exchange_rate: 0.85, avg_mcmeal: 9.15, avg_airfare: 1010.08, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 6, currency: "USD", start_exchange_rate: 1, avg_mcmeal: 7.00, avg_airfare: 315.80, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 7, currency: "EUR", start_exchange_rate: 0.85, avg_mcmeal: 9.33, avg_airfare: 1024.00, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 8, currency: "MXN", start_exchange_rate: 20.41, avg_mcmeal: 4.01, avg_airfare: 1004.64, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 9, currency: "NOK", start_exchange_rate: 8.10, avg_mcmeal: 13.53, avg_airfare: 1165.87, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 10, currency: "MAD", start_exchange_rate: 9.47, avg_mcmeal: 5.27, avg_airfare: 1232.97, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 11, currency: "CNY", start_exchange_rate: 6.40, avg_mcmeal: 4.06, avg_airfare: 1067.78, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 12, currency: "EUR", start_exchange_rate: 0.85, avg_mcmeal: 7.00, avg_airfare: 5381.24, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 13, currency: "CAD", start_exchange_rate: 1.29, avg_mcmeal: 7.73, avg_airfare: 221.80, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 14, currency: "HRK", start_exchange_rate: 6.30, avg_mcmeal: 5.54, avg_airfare: 1034.51, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 15, currency: "ARS", start_exchange_rate: 24.93, avg_mcmeal: 6.41, avg_airfare: 2769.27, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 16, currency: "JPY", start_exchange_rate: 109.83, avg_mcmeal: 6.18, avg_airfare: 1087.41, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 17, currency: "GBP", start_exchange_rate: 0.75, avg_mcmeal: 7.99, avg_airfare: 1057.44, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 18, currency: "ZAR", start_exchange_rate: 12.76, avg_mcmeal: 4.69, avg_airfare: 1483.98, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 19, currency: "KRW", start_exchange_rate: 1071.28, avg_mcmeal: 5.62, avg_airfare: 1092.00, avg_hotel: 0)
DestinationCostIndex.create(destination_id: 20, currency: "EUR", start_exchange_rate: 0.85, avg_mcmeal: 9.35, avg_airfare: 1076.89, avg_hotel: 0)
